name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: test
      run: |
        cd ..

      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
